### ISSUE TITLE
Rdkit daylight

### ISSUE THREAD

**Issue by ctr26** [paccanarolab/Side-effect-Frequencies#1]
Hi,

You mention in your paper that you use rdkit's algorithm for creating daylight feature vectors but I don't see that code in here. Is this done offline?

Craig

**Comment by diegogalpy** [comment]
Hi Craig,

To get the fingerprints from the SMILES notation, you can check the examples in  https://www.rdkit.org/docs/GettingStartedInPython.html

Best,
Diego

**Comment by ctr26** [comment]
I thought that daylight fingerprints were c++ only
